spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jonenxs/config-repo
          username: 570141370@qq.com
          password: 1451619620a
  rabbitmq:
    addresses: 119.27.187.114:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/